# Connect Matomo Release Action
#
# Builds the release archives, publishes a GitHub release and deploys the
# plugin to the wordpress.org SVN repository (slug: wp-piwik).
#
# Required GitHub secrets:
#
# RELEASE_PASSWORD  |  password that needs to be provided to start the action
# GITHUB_TOKEN  |  github release token to publish (provided automatically)
# SVN_USERNAME  | the svn username to publish a new plugin release
# SVN_PASSWORD  | the svn password to publish a new plugin release

name: Build release

permissions:
  actions: none
  checks: none
  contents: write  # required to create tag and release
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false
        default: ''
      password:
        description: 'Release password'
        required: true
      force:
        description: 'Force (0 or 1)'
        required: false
        default: 0

env:
  RELEASE_PASSWORD: ${{ secrets.RELEASE_PASSWORD }}

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: "Check release password"
        if: ${{ github.event.inputs.password != env.RELEASE_PASSWORD }}
        uses: actions/github-script@v7
        with:
          script: |
              core.setFailed('Release password didn\'t match.')
      - name: "Check if user is allowed"
        if: ${{ github.actor != 'mattab' && github.actor != 'tsteur' && github.actor != 'diosmosis' }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('User is not allowed to release.')
      - run: |
          sudo apt-get install -y subversion
          svn --version
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          token: ${{ secrets.GITHUB_TOKEN }} # for pushing to protected branch
          submodules: true
          persist-credentials: false
      - name: "Check tag"
        run: ./scripts/check_tag.sh
        env:
          VERSION_TO_RELEASE: ${{ github.event.inputs.version }}
      - name: "Extract changelog"
        id: changelog
        run: ./scripts/extract_changelog.sh
        env:
          # set in check_tag.sh
          version: "$version"
      - name: "Build releases"
        run: ./scripts/build_releases.sh
        env:
          # set in check_tag.sh
          version: "$version"
      - name: "Create release"
        uses: ncipollo/release-action@c4bf6c1ab090090498fb7f3ddc9f99ba5ab619b9
        with:
            artifacts: "wp-piwik-${{ env.version }}.*"
            allowUpdates: false
            tag: ${{ env.version }}
            body: ${{ steps.changelog.outputs.notes }}
            prerelease: false
            token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Deploy on wordpress"
        run: |
          ./scripts/deploy.sh "$version" "$PWD/wp-piwik-$version.tgz"
        shell: bash
        env:
          FORCE_DEPLOY: ${{ github.event.inputs.force }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
